include(CMakeParseArguments)

function(TurboQReactorRemoveMatchesFromList)
    set(options)
    set(oneValueArgs)
    set(multiValueArgs MATCHES)
    cmake_parse_arguments(TQR_PARSED "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    foreach (TQR_LIST ${TQR_PARSED_UNPARSED_ARGUMENTS})
        foreach (TQR_ENTRY ${${TQR_LIST}})
            foreach (TQR_MATCH ${TQR_PARSED_MATCHES})
                if (${TQR_ENTRY} MATCHES ${TQR_MATCH})
                    list(REMOVE_ITEM ${TQR_LIST} ${TQR_ENTRY})
                endif()
            endforeach()
        endforeach()
        set(${TQR_LIST} ${${TQR_LIST}} PARENT_SCOPE)
    endforeach()
endfunction()

function(TurboQReactorAddTestsFromSourceList)
    set(options)
    set(oneValueArgs PREFIX)
    set(multiValueArgs LIBS COMPILE_OPTIONS DEFINITIONS)

    cmake_parse_arguments(TQR_PARSED "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    foreach (TQR_LIST ${TQR_PARSED_UNPARSED_ARGUMENTS})
        foreach (TQR_ENTRY ${${TQR_LIST}})
            if (${TQR_ENTRY} MATCHES ".*_test.cpp")
                string(REGEX REPLACE "^.*\/(.*)_test\.cpp$" "\\1" testName "${TQR_ENTRY}")
                set(testName "${TQR_PARSED_PREFIX}-${testName}-test")

                add_executable(${testName} ${TQR_ENTRY})
                target_compile_options(${testName} PRIVATE ${TQR_PARSED_COMPILE_OPTIONS})
                target_compile_definitions(${testName} PRIVATE ${TQR_PARSED_DEFINITIONS})
                target_link_libraries(${testName} PRIVATE ${TQR_PARSED_LIBS})

                add_test(${testName} ${testName})
            endif()
        endforeach()
    endforeach()
endfunction()

function(TurboQReactorAddBenchmarksFromSourceList)
    set(options)
    set(oneValueArgs PREFIX)
    set(multiValueArgs LIBS COMPILE_OPTIONS LINK_OPTIONS DEFINITIONS)

    cmake_parse_arguments(TQR_PARSED "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    foreach (TQR_LIST ${TQR_PARSED_UNPARSED_ARGUMENTS})
        foreach (TQR_ENTRY ${${TQR_LIST}})
            if (${TQR_ENTRY} MATCHES ".*_bm.cpp")
                string(REGEX REPLACE "^.*\/(.*)_bm\.cpp$" "\\1" benchmarkName "${TQR_ENTRY}")
                set(benchmarkName "${TQR_PARSED_PREFIX}-${benchmarkName}-bm")

                add_executable(${benchmarkName} ${TQR_ENTRY})
                target_compile_options(${benchmarkName} PRIVATE ${TQR_PARSED_COMPILE_OPTIONS})
                target_compile_definitions(${benchmarkName} PRIVATE ${TQR_PARSED_DEFINITIONS})
                target_link_options(${benchmarkName} PRIVATE ${TQR_PARSED_LINK_OPTIONS})
                target_link_libraries(${benchmarkName} PRIVATE ${TQR_PARSED_LIBS})
            endif()
        endforeach()
    endforeach()
endfunction()

function(TurboQReactorExcludeTestsAndBenchmarksFromSourceList TQR_LIST)
    list(FILTER ${TQR_LIST} EXCLUDE REGEX ".*_test.cpp")
    list(FILTER ${TQR_LIST} EXCLUDE REGEX ".*_bm.cpp")
    set(${TQR_LIST} ${${TQR_LIST}} PARENT_SCOPE)
endfunction()
